### ISSUE TITLE
[Feature] Return request http headers and IP

### ISSUE THREAD

**Issue by AntonioSun** [Ananto30/mocker#1]
Hi, 

Nice project! 

Would you consider adding an option to return the request's http headers and IP back in a separated json field?

**Comment by AntonioSun** [comment]
Ah, answering specific requests like `/ip` & `/headers` might be better

**Comment by Ananto30** [comment]
Hello @AntonioSun , thanks 🙏

I don't get your request. Would you please provide an example?

**Comment by AntonioSun** [comment]
See https://httpbin.org/#/Request_inspection

I don't need it any more, I'm logging them in back end console now.
