### ISSUE TITLE
[Feature] regex support

### ISSUE THREAD

**Issue by AntonioSun** [Ananto30/mocker#3]
Need to be able to match HTTP request urls by regex.

Please consider. thx.

**Comment by Ananto30** [comment]
Why is that necessary? Are you looking for path params? Like `/users/123/books`?

**Comment by AntonioSun** [comment]
Yes, and also `/books?author=xxx&year=xxx` etc. I believe without regex, current implementation would fail, or maybe not, depending how fasthttp view it. I haven't check yet. But your're right, the new API way will surely be problematic.
